"""new version

Revision ID: f211a6550150
Revises: 9654ad52f3bf
Create Date: 2023-06-01 16:44:18.137645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f211a6550150'
down_revision = '9654ad52f3bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('superadmin')
    op.drop_index('ix_lesson_id', table_name='lesson')
    op.drop_table('lesson')
    op.drop_table('courses')
    op.drop_table('admins')
    op.drop_table('admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=15), nullable=False),
    sa.Column('password', sa.VARCHAR(length=10), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('date_last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['superadmin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=15), nullable=False),
    sa.Column('password', sa.VARCHAR(length=10), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('date_last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['superadmin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('lines_of_work', sa.VARCHAR(), nullable=True),
    sa.Column('specific_objetives', sa.VARCHAR(), nullable=True),
    sa.Column('type_of_course', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('title_resource', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lesson_id', 'lesson', ['id'], unique=False)
    op.create_table('superadmin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=15), nullable=False),
    sa.Column('password', sa.VARCHAR(length=10), nullable=False),
    sa.Column('email', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
